services:
  redis:
    container_name: demo-redis
    image: redis:7
    env_file:
      - ./.envs/.env
    ports:
      - "6378:6379"
    restart: always

networks:
 default:
   external: true
   name: rpine_dex_bot_shared-web
